# Generated by Django 3.0.7 on 2020-10-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tech_blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image1', models.ImageField(upload_to='tech')),
                ('image2', models.ImageField(upload_to='')),
                ('desc1', models.TextField()),
                ('desc2', models.TextField()),
                ('special_artice', models.BooleanField(default=False)),
            ],
        ),
    ]
