# Generated by Django 3.0.7 on 2020-10-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech_blog',
            name='desc3',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tech_blog',
            name='image3',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
