# Generated by Django 3.0.7 on 2020-10-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0002_auto_20201010_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech_blog',
            name='image2',
            field=models.ImageField(upload_to='tech'),
        ),
        migrations.AlterField(
            model_name='tech_blog',
            name='image3',
            field=models.ImageField(upload_to='tech'),
        ),
    ]
