# Generated by Django 3.0.7 on 2020-10-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0003_auto_20201011_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tech_blog',
            name='image1',
        ),
        migrations.AddField(
            model_name='tech_blog',
            name='cover_image',
            field=models.ImageField(default=0, upload_to='tech/coverimage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tech_blog',
            name='more',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tech_blog',
            name='desc1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tech_blog',
            name='desc2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tech_blog',
            name='desc3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tech_blog',
            name='image2',
            field=models.ImageField(upload_to='tech/image2'),
        ),
        migrations.AlterField(
            model_name='tech_blog',
            name='image3',
            field=models.ImageField(upload_to='tech/image3'),
        ),
    ]
