# Generated by Django 3.0.7 on 2020-10-19 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tech', '0006_auto_20201016_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech_blog',
            name='likes',
            field=models.ManyToManyField(related_name='blog_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
