# Generated by Django 3.0.7 on 2020-10-19 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0007_tech_blog_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tech_blog',
            name='likes',
        ),
    ]
