# Generated by Django 3.0.7 on 2020-10-20 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0009_auto_20201020_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liked',
        ),
        migrations.DeleteModel(
            name='AnswerLiker',
        ),
    ]
