# Generated by Django 3.0.7 on 2020-10-20 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tech', '0011_auto_20201020_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tech_blog',
            name='likes',
        ),
        migrations.AddField(
            model_name='tech_blog',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='Liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
