# Generated by Django 3.0.7 on 2020-10-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0012_auto_20201020_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tech_blog',
            name='liked',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
